kind: Application

server:
  port: 8081



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices?currentSchema=user_service
    username: vivekkumar
    password: 1234
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:configserver:http://localhost:8085
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instance:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instance:
     userRateLimiter:
       limit-refresh-period: 4s
       limit-for-period: 2
       timeout-duration: 0s
